# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.
**Preparing Data (the Cars Dataset)**
"""

!ls "/content/drive/My Drive/Deep Learning/GAN Retrieval/"

# Download the dataset into the desired directory
!wget -P "/content/drive/My Drive/Deep Learning/GAN Retrieval/" http://imagenet.stanford.edu/internal/car196/cars_train.tgz
!wget -P "/content/drive/My Drive/Deep Learning/GAN Retrieval/" http://imagenet.stanford.edu/internal/car196/cars_test.tgz
!wget -P "/content/drive/My Drive/Deep Learning/GAN Retrieval/" https://ai.stanford.edu/~jkrause/cars/car_devkit.tgz

# Unzip the files
import shutil
shutil.unpack_archive("/content/drive/My Drive/Deep Learning/GAN Retrieval/cars_train.tgz", "/content/drive/My Drive/Deep Learning/GAN Retrieval/Dataset")
shutil.unpack_archive("/content/drive/My Drive/Deep Learning/GAN Retrieval/cars_test.tgz", "/content/drive/My Drive/Deep Learning/GAN Retrieval/Dataset")
shutil.unpack_archive("/content/drive/My Drive/Deep Learning/GAN Retrieval/car_devkit.tgz", "/content/drive/My Drive/Deep Learning/GAN Retrieval/Dataset")